Repository apache/geode, pull requests merged in 2022-05, with the labels that each got.

#7637 GEODE-10263: add additional import for VMStats50
  geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptions.java
Labels: jdk17

#7671 GEODE-10284: Add partition-listener option to gfsh create region command (#7666)
  geode-core/src/main/java/org/apache/geode/management/internal/i18n/CliStrings.java
  geode-docs/tools_modules/gfsh/command-pages/create.html.md.erb
  geode-gfsh/src/distributedTest/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommandDUnitTest.java
  geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/GfshParserAutoCompletionIntegrationTest.java
  geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/CreateRegionCommand.java
Labels: backport

#7699 GEODE-10315: removed unneeded add-opens
  geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptions.java
Labels: jdk17

#7303 GEODE-9987: Refactored/Removal of deprecated APIs
  geode-core/src/distributedTest/java/org/apache/geode/distributed/HostedLocatorsDUnitTest.java
Labels: windows
