Repository apache/geode, pull requests merged in 2022-06, with the labels that each got.

#7772 GEODE-10321: Acceptance test for Geode access to JDK internals
  geode-assembly/src/acceptanceTest/java/org/apache/geode/jdk/JdkEncapsulationTest.java
  geode-assembly/src/acceptanceTest/java/org/apache/geode/jdk/TraverseEncapsulatedJdkObject.java
  geode-junit/src/main/java/org/apache/geode/test/util/JarUtils.java
Labels: windows, jdk8, jdk17, windows-jdk17

#7787 Revert "GEODE-9632: Allow INDEX_THRESHOLD_SIZE System property to ove…
  geode-core/src/integrationTest/java/org/apache/geode/cache/query/functional/LimitClauseJUnitTest.java
  geode-core/src/integrationTest/java/org/apache/geode/cache/query/functional/NonDistinctOrderByReplicatedJUnitTest.java
  geode-core/src/integrationTest/java/org/apache/geode/cache/query/functional/OrderByReplicatedJUnitTest.java
  geode-core/src/main/java/org/apache/geode/cache/query/internal/AbstractGroupOrRangeJunction.java
  geode-core/src/main/java/org/apache/geode/cache/query/internal/QueryUtils.java
  geode-core/src/main/java/org/apache/geode/cache/query/internal/index/CompactRangeIndex.java
  geode-core/src/main/java/org/apache/geode/cache/query/internal/index/HashIndex.java
  geode-core/src/main/java/org/apache/geode/cache/query/internal/index/IndexManager.java
  geode-core/src/main/java/org/apache/geode/cache/query/internal/index/PrimaryKeyIndex.java
  geode-core/src/main/java/org/apache/geode/cache/query/internal/index/RangeIndex.java
  geode-cq/src/distributedTest/java/org/apache/geode/cache/query/dunit/QueryWithRangeIndexDUnitTest.java
Labels: windows, windows-jdk17, windows-jdk8

#7779 GEODE-6504: Instant class used.
  geode-core/src/integrationTest/java/org/apache/geode/cache/RegionExpirationIntegrationTest.java
Labels: windows, windows-jdk17, windows-jdk8

#7805 GEODE-10387: bump dependencies
  boms/geode-all-bom/src/test/resources/expected-pom.xml
  build-tools/geode-dependency-management/src/main/groovy/org/apache/geode/gradle/plugins/DependencyConstraints.groovy
  dev-tools/dependencies/bump.sh
  geode-assembly/src/integrationTest/resources/assembly_content.txt
  geode-assembly/src/integrationTest/resources/gfsh_dependency_classpath.txt
  geode-assembly/src/main/dist/LICENSE
  geode-server-all/src/integrationTest/resources/dependency_classpath.txt
Labels: windows, jdk8, jdk17
