Repository apache/geode, pull requests merged in 2022-04, with the labels that each got.

#7512 GEODE-10125: Switch Radish data structures to use DataSerializable
  geode-for-redis/src/integrationTest/resources/org/apache/geode/codeAnalysis/sanctionedDataSerializables.txt
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/RedisConstants.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/AbstractRedisData.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/NullRedisData.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisData.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisHash.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisKey.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSet.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisSortedSet.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisString.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/AddByteArrayDoublePairs.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/AddByteArrayPairs.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/AddByteArrays.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/AddByteArraysTail.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/RemoveByteArrays.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/RemoveElementsByIndex.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/ReplaceByteArrayAtOffset.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/ReplaceByteArrayDoublePairs.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/ReplaceByteArrays.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/delta/ReplaceByteAtOffset.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/pubsub/Publisher.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/services/cluster/RedisMemberInfo.java
  geode-for-redis/src/main/resources/META-INF/services/org.apache.geode.internal.serialization.DataSerializableFixedIdRegistrant
  geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/RedisHashTest.java
  geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/RedisListTest.java
  geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSetTest.java
  geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/RedisSortedSetTest.java
  geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/RedisStringTest.java
  geode-serialization/src/main/java/org/apache/geode/internal/serialization/DataSerializableFixedID.java
Labels: redis

#7521 GEODE-10116: Enable Redis TCL tests for Lists
  ci/scripts/execute_redis_tests.sh
  geode-for-redis/src/acceptanceTest/resources/0001-configure-redis-tests.patch
Labels: redis

#7478 GEODE-10126: Replace Geode for Redis properties with system properties
  geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
  geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
  geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
  geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
  geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
  geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigImplTest.java
  geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/GeodeRedisServerStartupAcceptanceTest.java
  geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/GeodeRedisServerStartupUsingGfshAcceptanceTest.java
  geode-for-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
  geode-for-redis/src/commonTest/java/org/apache/geode/redis/TestRedisConfiguration.java
  geode-for-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/hash/HashesAndCrashesDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/key/RenameDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/RPushDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/sortedset/ZRemDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/sortedset/ZRemRangeByRankDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/string/MSetDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/string/MSetNXDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/auth/AuthWhileServersRestartDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionsAndCrashesDUnitTest.java
  geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/connection/AuthIntegrationTest.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/RedisConfiguration.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/SystemPropertyBasedRedisConfiguration.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/services/RegionProvider.java
Labels: redis

#7530 GEODE-10165: change how doSend handles SocketException
  geode-membership/src/main/java/org/apache/geode/distributed/internal/membership/gms/messenger/Transport.java
Labels: jdk17

#7572 GEODE-10225: Gfsh start commands add exports on JDK 11+
  geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandIntegrationTest.java
  geode-assembly/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartServerCommandIntegrationTest.java
  geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandTest.java
  geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartServerCommandTest.java
  geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/VerifyCommandLine.java
  geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptions.java
  geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommand.java
  geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartServerCommand.java
  geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptionsTest.java
Labels: windows, jdk8, jdk17

#7566 GEODE-10204: Add Test Coverage for SizeableByteArrayList
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/collections/SizeableByteArrayList.java
  geode-for-redis/src/test/java/org/apache/geode/redis/internal/data/collections/SizeableByteArrayListTest.java
Labels: redis

#7570 GEODE-10146: Make GradleBuildWithGeodeCoreAcceptanceTest run on JDK 17
  geode-assembly/src/acceptanceTest/java/org/apache/geode/management/internal/rest/GradleBuildWithGeodeCoreAcceptanceTest.java
Labels: windows, jdk8, jdk17

#7585 GEODE-10235: fix --maxHeap for java 17
  geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartLocatorCommandTest.java
  geode-assembly/src/test/java/org/apache/geode/management/internal/cli/commands/StartServerCommandTest.java
  geode-gfsh/build.gradle
  geode-gfsh/src/integrationTest/java/org/apache/geode/management/internal/cli/commands/StartMemberUtilsTest.java
  geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptions.java
  geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/StartMemberUtils.java
  geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptionsTest.java
Labels: jdk17

#7586 Revert "Revert "GEODE-10126: Replace Geode for Redis properties with system properties (#7478)" (#7576)"
  geode-core/src/main/java/org/apache/geode/distributed/ConfigurationProperties.java
  geode-core/src/main/java/org/apache/geode/distributed/internal/AbstractDistributionConfig.java
  geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfig.java
  geode-core/src/main/java/org/apache/geode/distributed/internal/DistributionConfigImpl.java
  geode-core/src/main/java/org/apache/geode/internal/cache/GemFireCacheImpl.java
  geode-core/src/test/java/org/apache/geode/distributed/internal/DistributionConfigImplTest.java
  geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/GeodeRedisServerStartupAcceptanceTest.java
  geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/internal/commands/executor/GeodeRedisServerStartupUsingGfshAcceptanceTest.java
  geode-for-redis/src/commonTest/java/org/apache/geode/redis/GeodeRedisServerRule.java
  geode-for-redis/src/commonTest/java/org/apache/geode/redis/TestRedisConfiguration.java
  geode-for-redis/src/commonTest/java/org/apache/geode/test/dunit/rules/RedisClusterStartupRule.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/hash/HashesAndCrashesDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/key/RenameDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/RPushDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/sortedset/ZRemDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/sortedset/ZRemRangeByRankDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/string/MSetDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/string/MSetNXDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/executor/auth/AuthWhileServersRestartDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/session/SessionsAndCrashesDUnitTest.java
  geode-for-redis/src/integrationTest/java/org/apache/geode/redis/internal/commands/executor/connection/AuthIntegrationTest.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisServer.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/GeodeRedisService.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/RedisConfiguration.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/SystemPropertyBasedRedisConfiguration.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/netty/NettyRedisServer.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/services/RegionProvider.java
Labels: redis

#7591 GEODE-10185: fix MemoryOverheadIntegrationTest for jdk17
  geode-core/src/main/java/org/apache/geode/internal/size/ObjectGraphSizer.java
  geode-core/src/main/java/org/apache/geode/internal/size/ObjectTraverser.java
  geode-core/src/test/java/org/apache/geode/internal/size/ObjectTraverserJUnitTest.java
Labels: jdk17

#7593 GEODE-10238: add open for jetty9 on java 17
  geode-for-redis/src/acceptanceTest/java/org/apache/geode/redis/GeodeRedisServerStartupAcceptanceTest.java
  gradle/test.gradle
Labels: jdk17

#7595 GEODE-10197: fix test for jdk17
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/OutOfMemoryDUnitTest.java
Labels: jdk17

#7579 GEODE-10161: Remove unnecessary synchronization from RedisList
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LInsertDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LPopDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LPushDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LRemDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/LTrimDUnitTest.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/internal/commands/executor/list/RPopDUnitTest.java
  geode-for-redis/src/main/java/org/apache/geode/redis/internal/data/RedisList.java
Labels: redis

#7606 GEODE-10246: fix OutOfMemoryDUnitTest for jdk17
  geode-core/src/main/java/org/apache/geode/internal/cache/control/HeapMemoryMonitor.java
  geode-for-redis/src/distributedTest/java/org/apache/geode/redis/OutOfMemoryDUnitTest.java
Labels: jdk17

#7582 GEODE-10184: Open status file for reading before handling request to avoid race conditions when accessing the file
  geode-core/src/main/java/org/apache/geode/internal/process/ControlFileWatchdog.java
  geode-core/src/main/java/org/apache/geode/internal/process/FileControllableProcess.java
Labels: windows

#7632 GEODE-10263: add opens required by geode features
  geode-gfsh/src/main/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptions.java
  geode-gfsh/src/test/java/org/apache/geode/management/internal/cli/commands/MemberJvmOptionsTest.java
Labels: jdk17
